using System.Globalization;
using System.Text;

namespace Xdiff.UnitTests;

/// <summary>
/// Byte-exact regressions generated by generate-coverage-goldens.sh against
/// standalone xdiff. Expected output is never decoded, including raw-byte cases.
/// </summary>
public class CoverageGoldenTests
{
    [Theory]
    [InlineData("myers_forward", 300, 600)]
    [InlineData("myers_backward", 600, 300)]
    public void UnifiedDiff_HeuristicAcceptance_MatchesCGolden(string name, int front, int back)
    {
        // 68,003 diagonals give a 512 search budget, exceeding HeurMinCost=256.
        // Reversed end blocks delay the long interior snake until the heuristic
        // can accept it, from the forward or backward direction respectively.
        const int count = 34000;
        var oldText = new StringBuilder();
        var newText = new StringBuilder();
        for (int i = 0; i < count; i++)
        {
            AppendLine(oldText, i);
            int mapped = i < front ? front - i - 1 : i >= count - back ? 2 * count - back - i - 1 : i;
            AppendLine(newText, mapped);
        }

        byte[] actual = Diff.UnifiedDiff(Encoding.UTF8.GetBytes(oldText.ToString()), Encoding.UTF8.GetBytes(newText.ToString()));

        Assert.Equal(Load(name, "expected"), actual);
    }

    [Theory]
    [InlineData("function_multiple_changes", false)]
    [InlineData("function_eof_without_header", false)]
    [InlineData("function_no_header", false)]
    [InlineData("function_append_after_body", false)]
    [InlineData("function_raw_bytes", false)]
    [InlineData("function_recover_blank", true)]
    [InlineData("function_skip_then_recover_blank", true)]
    public void UnifiedDiff_FunctionContext_MatchesCGolden(string name, bool ignoreBlankLines)
    {
        var options = new DiffOptions
        {
            ContextLines = 0,
            FunctionContext = true,
            IncludeFunctionNames = true,
            IgnoreBlankLines = ignoreBlankLines,
            FunctionMatcher = static line => !line.IsEmpty && line[0] == (byte)'#',
        };

        Assert.Equal(Load(name, "expected"), Diff.UnifiedDiff(Load(name, "old"), Load(name, "new"), options));
    }

    public static TheoryData<string, DiffAlgorithm, bool> RepeatedCases
    {
        get
        {
            var cases = new TheoryData<string, DiffAlgorithm, bool>();
            foreach (string name in new[] { "repeated_cleanup", "repeated_discard", "repeated_slide", "repeated_slide_up", "repeated_raw_bytes" })
            {
                foreach (DiffAlgorithm algorithm in new[] { DiffAlgorithm.Myers, DiffAlgorithm.Minimal, DiffAlgorithm.Patience, DiffAlgorithm.Histogram })
                {
                    cases.Add(name, algorithm, false);
                    cases.Add(name, algorithm, true);
                }
            }

            return cases;
        }
    }

    [Theory]
    [MemberData(nameof(RepeatedCases))]
    public void UnifiedDiff_RepeatedRecords_MatchesCGolden(string name, DiffAlgorithm algorithm, bool indent)
    {
        var options = new DiffOptions { Algorithm = algorithm, IndentHeuristic = indent };
        string variant = $"{name}_{algorithm.ToString().ToLowerInvariant()}{(indent ? "_indent" : string.Empty)}";

        Assert.Equal(Load(variant, "expected"), Diff.UnifiedDiff(Load(name, "old"), Load(name, "new"), options));
    }

    private static byte[] Load(string name, string part) => FixtureLoader.LoadBytes($"Fixtures/coverage/{name}.{part}.bin");

    private static void AppendLine(StringBuilder builder, int number)
    {
        builder.Append("line_").Append(number.ToString("D5", CultureInfo.InvariantCulture)).Append('\n');
    }
}
